### ISSUE TITLE
Some PRs had broken CI

### ISSUE THREAD

**Issue by nathanshammah** [tghp/unitary-fund#21]
Some PRs had broken CI, such as:
- https://github.com/tghp/unitary-fund/pull/9
- https://github.com/tghp/unitary-fund/pull/10
- https://github.com/tghp/unitary-fund/pull/16

We have merged them, hoping this is fine, @joshdavenport.

**Comment by joshdavenport** [comment]
Thanks @nathanshammah I suspect then that the .md files in those PRs are the culprits with invalid YAML.

https://github.com/tghp/unitary-fund/pull/9 — This is probably the colon in the title, as colon is used to delimit the key/value, the YAML parser gets confused by the colon in the title itself
https://github.com/tghp/unitary-fund/pull/10 — Same as above
https://github.com/tghp/unitary-fund/pull/16 — Not sure about this one, will get back to you

**Comment by nathanshammah** [comment]
Hi @joshdavenport, not sure also why the grants PR #27 got CI failing and whether it renders on the website correctly.
