### ISSUE TITLE
Add links to research items

### ISSUE THREAD

**Issue by nathanshammah** [tghp/unitary-fund#39]
Add links to research items. See research page [here](https://unitary-fund-git-nathanshammah-patch-5-the-glasshouse-project.vercel.app/research/publications/) and the current one here: https://unitary.fund/research.html. 

Can you please add the links @srilakshmip03 and @QuantumAli?

**Comment by QuantumAli** [comment]
No worries, will do!

**Comment by WrathfulSpatula** [comment]
@QuantumAli I think you did this already, but is that the case? If so, we can close the issue.

**Comment by QuantumAli** [comment]
Yes, that was apart of the microgrants links that I merged!
