### ISSUE TITLE
Intra-year grant order should be reversed

### ISSUE THREAD

**Issue by WrathfulSpatula** [tghp/unitary-fund#51]
Hi, thanks for closing every issue so far! I think we might have just one point to address, before we're ready for launch.

In the "Grants" view, years are listed by descending chronological sorting order, which is great. However, I think we want the grant dates within single years to _also_ sort in descending chronological order. (Currently, years are descending, but grants within years are chronologically ascending.)

**Comment by joshdavenport** [comment]
Good spot, should be good now!
