### ISSUE TITLE
Repo access for Unitary Fund interns

### ISSUE THREAD

**Issue by WrathfulSpatula** [tghp/unitary-fund#7]
Hi, thanks for all the work you folks are doing on redesigning and re-implementing the Unitary Fund website!

Nathan at Unitary Fund tells me we need help converting some of the HTML-based blog and events content to markdown. We think this would be a great task to get our new interns started, learning GitHub and basic agile methodology!

These are our two new interns:
Ali Gedawi, agedawi@nyit.edu
Srila Palanikumar, srila.palanikumar@gmail.com

Can we please get them repository access, so they can start converting content to markdown? (Thanks again!)

**Comment by nathanshammah** [comment]
Thanks @joshdavenport, this is addressed.
